PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "Name":"ktbossupdated" ,
    "Description":"tesdsfsdtupda",
    "location": "vs cdfsdodeupda", 
    "DateTime":"2025-01-01T18:44:00.000Z"
}

